### ISSUE TITLE
Can't go get it.

### ISSUE THREAD

**Issue by superstas** [KenanBek/dbui#17]
Hi there, 
I've got a small issue when I try to install it.

```sh
❯ go get github.com/KenanBek/dbui
go: downloading github.com/KenanBek/dbui v0.1.2
go get: github.com/KenanBek/dbui@none updating to
        github.com/KenanBek/dbui@v0.1.2: parsing go.mod:
        module declares its path as: dbui
                but was required as: github.com/KenanBek/dbui
```

**Comment by KenanBek** [comment]
Should be fixed now. I forget to change the mod name in `go.mod` when I made the repo public.

You might need to remove files in `src` before running `go get` again.

```
rm -rf $GOPATH/src/github.com/kenanbek/dbui
```

**Comment by xentec** [comment]
@KenanBek  This issue still persists, but in a slightly different form.
```
$ go install github.com/KenanBek/dbui@v0.7.0
go: github.com/KenanBek/dbui@v0.7.0: github.com/KenanBek/dbui@v0.7.0: parsing go.mod:
	module declares its path as: github.com/kenanbek/dbui
	        but was required as: github.com/KenanBek/dbui
```
